version: "3.3"

services:

  hadoop-master:
    image: local/hadoop-base:2.9.2
    hostname: hadoop-master
    container_name: hadoop-master
    volumes: 
      - ./data/node1:/data
    environment: 
      HADOOP_MASTER: hadoop-master
      SLAVES: "hadoop-master,hadoop-slave1,hadoop-slave2"
      CLUSTER_NAME: local
      MASTER: 'true'
    networks:
      - docker-local

  hadoop-slave1:
    image: local/hadoop-base:2.9.2
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    volumes: 
      - ./data/node2:/data
    environment: 
      HADOOP_MASTER: hadoop-master
    networks:
      - docker-local

  hadoop-slave2:
    image: local/hadoop-base:2.9.2
    hostname: hadoop-slave2
    container_name: hadoop-slave2
    volumes: 
      - ./data/node3:/data
    environment: 
      HADOOP_MASTER: hadoop-master
    networks:
      - docker-local

networks:
  docker-local:
    external: true