version: '3.3'

services:

  hadoop-master:
    image: local/hadoop-master:2.9.1
    hostname: hadoop-master
    container_name: hadoop-master
    environment: 
      HADOOP_MASTER: hadoop-master
      SLAVES: "hadoop-master,hadoop-slave1,hadoop-slave2"
    networks:
      - docker-local

  hadoop-slave1:
    image: local/hadoop-base:2.9.1
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    environment: 
      HADOOP_MASTER: hadoop-master
      SLAVES: "hadoop-master,hadoop-slave1,hadoop-slave2"
    networks:
      - docker-local

  hadoop-slave2:
    image: local/hadoop-base:2.9.1
    hostname: hadoop-slave2
    container_name: hadoop-slave2
    environment: 
      HADOOP_MASTER: hadoop-master
      SLAVES: "hadoop-master,hadoop-slave1,hadoop-slave2"
    networks:
      - docker-local

networks:
  docker-local:
    external: true